//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestTable
    {
        public int GuestID { get; set; }
        public string FirstName { get; set; }
        public string LastNAme { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        public string Email { get; set; }
        public string Guest { get; set; }
    }
}
